### ISSUE TITLE
环境缺少‘adbutil’，是不是少下了什么？

### ISSUE THREAD

**Issue by chenbq123** [nightmare-space/adb_kit#16]
[adb_kit-main] flutter pub get
Resolving dependencies...
Because adb_kit depends on adbutil from path which doesn't exist (could not find package adbutil at "../adbutil"), version solving failed.

**Comment by xizerlix** [comment]
Good afternoon. I agree with the question. Could you explain in more detail how to compile the project, provided that the pubspec contains a comment that it is necessary to remove termux_api_plugin, adb_kit_extension and remove compilation errors manually. Thank you in advance!

**Comment by mengyanshou** [comment]
移除dependency_override下的路径依赖，移除相关代码报错

**Comment by mengyanshou** [comment]
Has the problem been solved?

xizerlix ***@***.***> 于2023年10月2日周一 18:32写道：

**Comment by chenbq123** [comment]
我在小米5手机上运行这个应用，使用OTG线连接开发态的设备，发现识别不到设备。可能是什么原因？

**Comment by mengyanshou** [comment]
系统版本太低了，OTG至少要安卓7.0及以上
