### ISSUE TITLE
readme中的地址变成了菠菜网站

### ISSUE THREAD

**Issue by AoEiuV020** [nightmare-space/adb_kit#17]
http://nightmare.fun/YanTool/resources/ADBTool/?C=N;O=A

![Screenshot_2023-11-21-13-28-53-946_com android chrome](https://github.com/nightmare-space/adb_kit/assets/11682198/cb48e6d3-c296-41f4-b6af-f409248d959a)

**Comment by mengyanshou** [comment]
将域名更改成nightmare.press即可
