### ISSUE TITLE
Bug: macOS 版本在设备操作页面点击返回卡住

### ISSUE THREAD

**Issue by JiyeHoo** [nightmare-space/adb_kit#19]
复现流程：
- 打开一个连接的设备 item 新起一个标签
- 点击左上角的返回，页面崩溃

注意不是点击 item 右侧的箭头

另外，如果是点击 item 右侧箭头，即 不起新的标签页面进入设备操作，没有为 MacOS 的三个按钮留出位置，内容会覆盖上去。

页面 crash 的问题很影响使用，看到了您的文件分享 iOS App，希望这个 ADB 工具也能上架一下 macOS 的。

加油！

**Comment by mengyanshou** [comment]
能提pr吗，最近忙不过来

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: JiyeHoo ***@***.***>
Sent: Thursday, December 14, 2023 2:14:25 PM
To: nightmare-space/adb_kit ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nightmare-space/adb_kit] Bug: macOS 版本在设备操作页面点击返回卡住 (Issue #19)


复现流程：

  *   打开一个连接的设备 item 新起一个标签
  *   点击左上角的返回，页面崩溃

注意不是点击 item 右侧的箭头

另外，如果是点击 item 右侧箭头，即 不起新的标签页面进入设备操作，没有为 MacOS 的三个按钮留出位置，内容会覆盖上去。

页面 crash 的问题很影响使用，看到了您的文件分享 iOS App，希望这个 ADB 工具也能上架一下 macOS 的。

加油！

―

**Comment by mengyanshou** [comment]
如有问题，欢迎再次打开这个issue
