### ISSUE TITLE
push 速度太慢

### ISSUE THREAD

**Issue by quanjin9099** [nightmare-space/adb_kit#6]
我通过type-c线把两个安卓手机连接起来,建立好连接之后,开始push一个 apk文件(30M)到另外一台安卓手机上,过了大概7、8分钟, 进度才走到7%左右,而手机电已经掉了20%,怎么才能加快push速度?

**Comment by mengyanshou** [comment]
这的确是一个问题，目前还没有好的方法优化

**Comment by mengyanshou** [comment]
这个已经得到解决，我将关闭这个issue
