### ISSUE TITLE
windows 11上pty terminal 有点问题

### ISSUE THREAD

**Issue by hpp0hpp** [nightmare-space/adb_kit#9]
flutter: [GetX] Instance "IconController" has been created
flutter: [GetX] Instance "IconController" has been initialized
[ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: Bad state: Failed to create PTY: Failed to create process, stack trace: #0      new Pty.start
package:flutter_pty/flutter_pty.dart:123
#1      Global.initTerminal
package:adb_tool/…/instance/global.dart:74
#2      Global.initGlobal
package:adb_tool/…/instance/global.dart:195
#3      _ADBToolEntryPointState.init
package:adb_tool/main.dart:109
<asynchronous suspension>
#4      _FutureBuilderState._subscribe.<anonymous closure>
package:flutter/…/widgets/async.dart:627
<asynchronous suspension>

**Comment by mengyanshou** [comment]
fixed~

**Comment by hpp0hpp** [comment]
还是有问题, 系统是win11 @mengyanshou 
![image](https://user-images.githubusercontent.com/54829297/180821066-45426fc7-ad7a-47f4-b07e-f0645b0b9d1d.png)

**Comment by mengyanshou** [comment]
你是下载的吗，最新版还没有上传，只是修复了代码，需要本地编译

**Comment by mengyanshou** [comment]
新版下载地址 http://nightmare.fun/YanTool/resources/ADBTool/?C=N;O=A

**Comment by hpp0hpp** [comment]
> 新版下载地址 http://nightmare.fun/YanTool/resources/ADBTool/?C=N;O=A

我自己编译和下载你的这版都还是不行,你有windows环境吗? 可以试试
![image](https://user-images.githubusercontent.com/54829297/181041141-607055e6-0d4f-4697-ae55-ff797a40823b.png)

**Comment by mengyanshou** [comment]
描述清楚你的问题，windows pty的截图提供一下，我这边测试过windows，pty terminal是没问题的

**Comment by hpp0hpp** [comment]
> 描述清楚你的问题，windows pty的截图提供一下，我这边测试过windows，pty terminal是没问题的

@mengyanshou 

这里的代码在windows平台没有初始化adbshell
![image](https://user-images.githubusercontent.com/54829297/181566551-508c609d-7080-4658-a691-062a1f58016e.png)

传递给xterm_wrapper的pseudoTerminal为null

然后最终弄导致这里的对象为null
![image](https://user-images.githubusercontent.com/54829297/181568530-4203bc2a-acc2-4dae-b9f2-a352783efd9f.png)

**Comment by hpp0hpp** [comment]
如果吧判断是否windows平台的判断去掉,又会提示failed to create process
![image](https://user-images.githubusercontent.com/54829297/181569865-0e74fe49-ad21-434a-9803-e3f3717c64e5.png)

**Comment by mengyanshou** [comment]
ok，我这下明白了，等我后面分配时间修复，我以为是侧栏进去的pty terminal有问题

**Comment by hpp0hpp** [comment]
另外安装apk对路径有空格的不能支持
同时建议加上-r参数以方便安装

**Comment by mengyanshou** [comment]
-r参数是什么作用，空格我后面再修复，目前二级页面windows pty修复了，在dev分支上，晚些提交actions打包

**Comment by hpp0hpp** [comment]
> -r参数是什么作用，空格我后面再修复，目前二级页面windows pty修复了，在dev分支上，晚些提交actions打包

感谢感谢.

-r 参数是强制安装apk,即使已经存在.  否则有些apk已经存在,安装不上. 另外apk安装失败没有提示也不是特别友好.

**Comment by mengyanshou** [comment]
我先关闭这个issue
